"""LLM provider adapter: ollama | openai | mock."""

from __future__ import annotations

from typing import Protocol

import httpx

from app.config import Settings, get_settings


class LLMClient(Protocol):
    def complete(self, system: str, user: str) -> str: ...


class MockLLMClient:
    """Deterministic explainer for tests / offline demos."""

    def complete(self, system: str, user: str) -> str:
        # Prefer the deterministic draft embedded by the query service.
        marker = "Deterministic draft to preserve:\n"
        if marker in user:
            draft = user.split(marker, 1)[1].strip()
            return f"{draft}\n\n(Explanation generated by mock LLM; numbers unchanged.)"
        return "Mock LLM: see pre-computed ledger facts and discrepancy alerts."


class OllamaClient:
    def __init__(self, base_url: str, model: str, timeout: float = 25.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.timeout = timeout

    def complete(self, system: str, user: str) -> str:
        payload = {
            "model": self.model,
            "stream": False,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "options": {"num_predict": 256},
        }
        with httpx.Client(timeout=self.timeout) as client:
            response = client.post(f"{self.base_url}/api/chat", json=payload)
            response.raise_for_status()
            data = response.json()
        return data.get("message", {}).get("content", "")


class OpenAIClient:
    def __init__(self, api_key: str, model: str, timeout: float = 25.0) -> None:
        self.api_key = api_key
        self.model = model
        self.timeout = timeout

    def complete(self, system: str, user: str) -> str:
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "max_tokens": 400,
        }
        with httpx.Client(timeout=self.timeout) as client:
            response = client.post(
                "https://api.openai.com/v1/chat/completions",
                headers=headers,
                json=payload,
            )
            response.raise_for_status()
            data = response.json()
        return data["choices"][0]["message"]["content"]


def get_llm_client(settings: Settings | None = None) -> LLMClient:
    settings = settings or get_settings()
    provider = settings.llm_provider.lower()
    timeout = settings.llm_timeout_seconds
    if provider == "mock":
        return MockLLMClient()
    if provider == "openai":
        if not settings.openai_api_key:
            raise ValueError("OPENAI_API_KEY is required when LLM_PROVIDER=openai")
        return OpenAIClient(settings.openai_api_key, settings.openai_model, timeout=timeout)
    if provider == "ollama":
        return OllamaClient(settings.ollama_base_url, settings.ollama_model, timeout=timeout)
    raise ValueError(f"Unsupported LLM_PROVIDER: {settings.llm_provider}")
